/**
 * Utility functions for exporting data to Excel (.csv), Word (.doc), and printable PDF/Receipts.
 */

export function exportToCSV(dataOrFilename: any, headersOrFilename?: any, rows?: any) {
  let csvContent = '';
  let filename = 'BSWA_Export';

  if (Array.isArray(dataOrFilename) && typeof dataOrFilename[0] === 'object' && !Array.isArray(dataOrFilename[0])) {
    // Array of objects format: exportToCSV(arrayOfObjects, 'filename')
    filename = typeof headersOrFilename === 'string' ? headersOrFilename : 'BSWA_Export';
    const items = dataOrFilename;
    if (items.length === 0) return;
    const headers = Object.keys(items[0]);
    const headerRow = headers.map(h => `"${h.replace(/"/g, '""')}"`).join(',');
    const bodyRows = items.map(item =>
      headers.map(h => `"${String(item[h] ?? '').replace(/"/g, '""')}"`).join(',')
    );
    csvContent = [headerRow, ...bodyRows].join('\r\n');
  } else if (typeof dataOrFilename === 'string' && Array.isArray(headersOrFilename) && Array.isArray(rows)) {
    // Legacy format: exportToCSV(filename, headers, rows)
    filename = dataOrFilename;
    const headers = headersOrFilename as string[];
    const rowList = rows as (string | number)[][];
    csvContent = [
      headers.map(h => `"${h.replace(/"/g, '""')}"`).join(','),
      ...rowList.map(row =>
        row.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')
      )
    ].join('\r\n');
  }

  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToWord(filename: string, title: string, htmlContent: string) {
  const fullHtml = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>${title}</title>
        <style>
          body { font-family: 'Calibri', 'Arial', sans-serif; margin: 40px; color: #1a1a1a; line-height: 1.6; }
          h1 { color: #800020; border-bottom: 2px solid #d4af37; padding-bottom: 8px; font-size: 22pt; }
          h2 { color: #560c1b; margin-top: 20px; font-size: 16pt; }
          table { width: 100%; border-collapse: collapse; margin-top: 15px; }
          th { background-color: #800020; color: #ffffff; padding: 10px; border: 1px solid #999; text-align: left; }
          td { padding: 8px; border: 1px solid #ccc; font-size: 11pt; }
          .header-seal { text-align: center; margin-bottom: 30px; }
          .footer { margin-top: 50px; font-size: 10pt; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header-seal">
          <h1 style="margin:0;">BUDDHIST STUDENTS WELFARE ASSOCIATION (BSWA)</h1>
          <p style="margin:4px 0; font-size:13pt; font-weight:bold; color:#731326;">Dhaka University of Engineering & Technology (DUET), Gazipur</p>
          <p style="margin:0; font-size:10pt; color:#666;">Official Long-Term Digital Records Registry</p>
        </div>
        ${htmlContent}
        <div class="footer">
          <p>Generated by BSWA DUET Platform on ${new Date().toLocaleString()}. Verified and authorized document.</p>
        </div>
      </body>
    </html>
  `;

  const blob = new Blob(['\uFEFF' + fullHtml], { type: 'application/msword;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.setAttribute('download', `${filename}.doc`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export const exportToWordDoc = exportToWord;

export function exportToPrintablePDF(title: string, elementIdOrHtml: string) {
  let content = elementIdOrHtml;
  const el = document.getElementById(elementIdOrHtml);
  if (el) {
    content = el.innerHTML;
  }
  openPrintableDocument(title, content);
}

export function openPrintableDocument(title: string, contentHtml: string) {
  const printWindow = window.open('', '_blank', 'width=850,height=900');
  if (!printWindow) {
    // Fallback if popup blocked: print current view
    window.print();
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} - BSWA DUET</title>
        <style>
          @page { size: A4; margin: 20mm; }
          body {
            font-family: 'Helvetica Neue', Arial, sans-serif;
            color: #1a1a1a;
            margin: 0;
            padding: 24px;
            background: #fff;
          }
          .bswa-header {
            text-align: center;
            border-bottom: 2px solid #800020;
            padding-bottom: 16px;
            margin-bottom: 24px;
            position: relative;
          }
          .bswa-title {
            font-size: 20px;
            font-weight: bold;
            color: #800020;
            margin: 0;
            letter-spacing: 0.5px;
          }
          .bswa-sub {
            font-size: 14px;
            font-weight: 600;
            color: #333;
            margin: 4px 0;
          }
          .bswa-address {
            font-size: 11px;
            color: #666;
            margin: 0;
          }
          .gold-badge {
            display: inline-block;
            background: #fef3c7;
            color: #92400e;
            border: 1px solid #d4af37;
            padding: 3px 10px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
            margin-top: 6px;
          }
          .doc-table {
            width: 100%;
            border-collapse: collapse;
            margin: 16px 0;
          }
          .doc-table th {
            background-color: #f7f1e5;
            color: #800020;
            font-weight: bold;
            text-align: left;
            padding: 8px 12px;
            border: 1px solid #d4af37;
            font-size: 12px;
          }
          .doc-table td {
            padding: 8px 12px;
            border: 1px solid #e2e8f0;
            font-size: 12px;
          }
          .signature-section {
            margin-top: 60px;
            display: flex;
            justify-content: space-between;
          }
          .sign-box {
            text-align: center;
            border-top: 1px dashed #666;
            width: 200px;
            padding-top: 6px;
            font-size: 12px;
          }
          @media print {
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="no-print" style="background:#fef3c7; padding:12px; border:1px solid #d4af37; border-radius:6px; margin-bottom:20px; display:flex; justify-content:space-between; align-items:center;">
          <div>
            <strong>Official Document Preview</strong> - Click Print to save as PDF or physical print.
          </div>
          <button onclick="window.print()" style="background:#800020; color:white; border:none; padding:8px 18px; border-radius:4px; font-weight:bold; cursor:pointer;">
            Print / Save as PDF
          </button>
        </div>

        <div class="bswa-header">
          <h1 class="bswa-title">BUDDHIST STUDENTS WELFARE ASSOCIATION (BSWA)</h1>
          <p class="bswa-sub">Dhaka University of Engineering & Technology (DUET), Gazipur-1707</p>
          <p class="bswa-address">Official Long-Term Digital Platform Registry • ESTD: 1986 • Email: contact@bswa-duet.org</p>
          <div class="gold-badge">Official Certified Document</div>
        </div>

        ${contentHtml}

        <div class="signature-section">
          <div class="sign-box">
            <strong>Prepared / Recorded By</strong><br>
            <span style="font-size:10px; color:#666;">Executive Member, BSWA DUET</span>
          </div>
          <div class="sign-box">
            <strong>General Secretary</strong><br>
            <span style="font-size:10px; color:#666;">BSWA, DUET</span>
          </div>
          <div class="sign-box">
            <strong>President / Patron</strong><br>
            <span style="font-size:10px; color:#666;">BSWA, DUET</span>
          </div>
        </div>
      </body>
    </html>
  `);
  printWindow.document.close();
}
